
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package interpreter;

/** CUP generated class containing symbol constants. */
public class CupParserSym {
  /* terminals */
  public static final int GEQ = 21;
  public static final int LT = 18;
  public static final int MULTIPLY = 15;
  public static final int PLUS = 13;
  public static final int DEFINE = 5;
  public static final int TRUE = 3;
  public static final int IF = 4;
  public static final int GT = 19;
  public static final int ID = 23;
  public static final int OBRACKET = 9;
  public static final int CBRACKET = 10;
  public static final int EQUALS = 17;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int DIVIDE = 16;
  public static final int FALSE = 2;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int OBRACE = 11;
  public static final int OPAREN = 7;
  public static final int CPAREN = 8;
  public static final int CBRACE = 12;
  public static final int LEQ = 20;
  public static final int LAMBDA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FALSE",
  "TRUE",
  "IF",
  "DEFINE",
  "LAMBDA",
  "OPAREN",
  "CPAREN",
  "OBRACKET",
  "CBRACKET",
  "OBRACE",
  "CBRACE",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "EQUALS",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "NUMBER",
  "ID"
  };
}

